# Generated by Django 5.0.14 on 2026-08-02 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresados', '0004_evento'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='egresados.evento'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('solicitud_creada', 'Solicitud Creada'), ('solicitud_aprobada', 'Solicitud Aprobada'), ('solicitud_rechazada', 'Solicitud Rechazada'), ('pago_confirmado', 'Pago Confirmado'), ('examen_agendado', 'Examen Agendado'), ('examen_calificado', 'Examen Calificado'), ('evento_creado', 'Evento Creado'), ('evento_inscripcion', 'Inscripción a Evento'), ('evento_cancelacion', 'Cancelación de Inscripción')], max_length=30),
        ),
    ]
