# Generated by Django 5.0.14 on 2026-07-21 21:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supletorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante_nombre', models.CharField(max_length=150)),
                ('estudiante_email', models.EmailField(max_length=254)),
                ('fecha_parcial', models.DateField()),
                ('fecha_solicitud', models.DateField(default=django.utils.timezone.localdate)),
                ('profesor', models.CharField(max_length=150)),
                ('asignatura', models.CharField(max_length=150)),
                ('grupo', models.CharField(max_length=50)),
                ('id_programa', models.IntegerField()),
                ('programa_nombre', models.CharField(blank=True, max_length=150)),
                ('descripcion', models.TextField()),
                ('nota_revision', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('formato_pendiente', 'Formato pendiente'), ('comprobante_subido', 'Comprobante subido'), ('notificado_profesor', 'Notificado al profesor'), ('realizado', 'Realizado')], default='pendiente', max_length=30)),
                ('comprobante_pago', models.FileField(blank=True, null=True, upload_to='comprobantes_pago/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnexoSupletorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='anexos_supletorios/')),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('supletorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='supletorios.supletorio')),
            ],
        ),
    ]
