# Generated by Django 5.0.14 on 2026-07-23 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supletorios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supletorio',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Supletorio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anexosupletorio',
            name='supletorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='supletorios.supletorio'),
        ),
    ]
