# Generated by Django 5.0.14 on 2026-07-23 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresados', '0002_initial'),
        ('supletorios', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supletorio',
            name='id_programa',
        ),
        migrations.AddField(
            model_name='supletorio',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='egresados.programa'),
        ),
    ]
