# Generated by Django 5.0.14 on 2026-07-23 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supletorios', '0003_remove_supletorio_id_programa_supletorio_programa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='supletorio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supletorios', to=settings.AUTH_USER_MODEL),
        ),
    ]
