# Generated by Django 5.0.14 on 2026-07-25 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supletorios', '0004_alter_supletorio_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supletorio',
            name='fecha_examen_supletorio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supletorio',
            name='fecha_programacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supletorio',
            name='nota',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supletorio',
            name='nota_observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supletorio',
            name='programado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supletorios_programados', to=settings.AUTH_USER_MODEL),
        ),
    ]
