BEGIN;

INSERT INTO roles (codigo, nombre, descripcion) VALUES
    ('docente', 'Docente', 'Acceso a funciones academicas autorizadas.')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO programas_academicos (nombre, codigo, nivel, modalidad, sede)
VALUES ('Ingenieria de Sistemas', 'ING-SIS', 'pregrado', 'presencial', 'Buenaventura')
ON CONFLICT (codigo) DO NOTHING;

-- Usuarios
INSERT INTO usuarios (email, password_hash, nombres, apellidos, estado, created_at, updated_at) VALUES ('alvasquez@unipacifico.edu.co', 'seed-placeholder', 'Aura', 'Liliana Vasquez', 'activo', now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO usuarios (email, password_hash, nombres, apellidos, estado, created_at, updated_at) VALUES ('cariascos@unipacifico.edu.co', 'seed-placeholder', 'Carlos', 'Anibal Riascos Hurtado', 'activo', now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO usuarios (email, password_hash, nombres, apellidos, estado, created_at, updated_at) VALUES ('danielhb@unipacifico.edu.co', 'seed-placeholder', 'Daniel', 'Hurtado Bustos', 'activo', now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO usuarios (email, password_hash, nombres, apellidos, estado, created_at, updated_at) VALUES ('eandrade@unipacifico.edu.co', 'seed-placeholder', 'Eder', 'Joaquin Gamboa Andrade', 'activo', now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO usuarios (email, password_hash, nombres, apellidos, estado, created_at, updated_at) VALUES ('esolisc@unipacifico.edu.co', 'seed-placeholder', 'Engelberto', 'Solis Caicedo', 'activo', now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO usuarios (email, password_hash, nombres, apellidos, estado, created_at, updated_at) VALUES ('evalois@unipacifico.edu.co', 'seed-placeholder', 'Euclinia', 'Valois Becerra', 'activo', now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO usuarios (email, password_hash, nombres, apellidos, estado, created_at, updated_at) VALUES ('glucio@unipacifico.edu.co', 'seed-placeholder', 'Gonzalo', 'Andres Lucio Lopez', 'activo', now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO usuarios (email, password_hash, nombres, apellidos, estado, created_at, updated_at) VALUES ('hmorenp@unipacifico.edu.co', 'seed-placeholder', 'Heladio', 'Moreno Gonzalez', 'activo', now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO usuarios (email, password_hash, nombres, apellidos, estado, created_at, updated_at) VALUES ('hbenitez@unipacifico.edu.co', 'seed-placeholder', 'Henry', 'Benitez Lemos', 'activo', now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO usuarios (email, password_hash, nombres, apellidos, estado, created_at, updated_at) VALUES ('hernan hildelberg gomez estupiñan', 'seed-placeholder', 'Hernan', 'Hildelberg Gomez Estupinan', 'activo', now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO usuarios (email, password_hash, nombres, apellidos, estado, created_at, updated_at) VALUES ('jhon cleyber vivas banguera', 'seed-placeholder', 'Jhon', 'Cleyber Vivas Banguera', 'activo', now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO usuarios (email, password_hash, nombres, apellidos, estado, created_at, updated_at) VALUES ('jjmurilloflorez@unipacifico.edu.co', 'seed-placeholder', 'Jhon', 'Jairo Murillo Florez', 'activo', now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO usuarios (email, password_hash, nombres, apellidos, estado, created_at, updated_at) VALUES ('jwcaicedo@unipacifico.edu.co', 'seed-placeholder', 'Jose', 'Walter Caicedo Arboleda', 'activo', now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO usuarios (email, password_hash, nombres, apellidos, estado, created_at, updated_at) VALUES ('jcmolina@unipacifico.edu.co', 'seed-placeholder', 'Juan', 'Carlos Molina Lozano', 'activo', now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO usuarios (email, password_hash, nombres, apellidos, estado, created_at, updated_at) VALUES ('jmanuelh@unipacifico.edu.co', 'seed-placeholder', 'Juan', 'Manuel Hurtado Angulo', 'activo', now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO usuarios (email, password_hash, nombres, apellidos, estado, created_at, updated_at) VALUES ('lafigueroa@unipacifico.edu.co', 'seed-placeholder', 'Luis', 'Angel Figueroa Ocoro', 'activo', now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO usuarios (email, password_hash, nombres, apellidos, estado, created_at, updated_at) VALUES ('pedroangulo@unipacifico.edu.co', 'seed-placeholder', 'Pedro', 'Alfredo Angulo Palacios', 'activo', now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO usuarios (email, password_hash, nombres, apellidos, estado, created_at, updated_at) VALUES ('sandra patricia rivera guzman', 'seed-placeholder', 'Sandra', 'Patricia Rivera Guzman', 'activo', now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO usuarios (email, password_hash, nombres, apellidos, estado, created_at, updated_at) VALUES ('vhvalencia@unipacifico.edu.co', 'seed-placeholder', 'Victor', 'Hugo Valencia Biafara', 'activo', now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO usuarios (email, password_hash, nombres, apellidos, estado, created_at, updated_at) VALUES ('wcastillo@unipacifico.edu.co', 'seed-placeholder', 'William', 'Castillo Lopez', 'activo', now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO usuarios (email, password_hash, nombres, apellidos, estado, created_at, updated_at) VALUES ('waquinonezv@unipacifico.edu.co', 'seed-placeholder', 'Wilman', 'Andres Quinonez Valencia', 'activo', now(), now()) ON CONFLICT (email) DO NOTHING;
INSERT INTO usuarios (email, password_hash, nombres, apellidos, estado, created_at, updated_at) VALUES ('ykcaicedo@unipacifico.edu.co', 'seed-placeholder', 'Yowanna', 'Karina Caicedo Guerrero', 'activo', now(), now()) ON CONFLICT (email) DO NOTHING;

-- Asignar rol docente
INSERT INTO usuario_roles (usuario_id, rol_id, asignado_por) SELECT u.id, r.id, NULL FROM usuarios u JOIN roles r ON r.codigo = 'docente' WHERE u.email IN ('alvasquez@unipacifico.edu.co', 'cariascos@unipacifico.edu.co', 'danielhb@unipacifico.edu.co', 'eandrade@unipacifico.edu.co', 'esolisc@unipacifico.edu.co', 'evalois@unipacifico.edu.co', 'glucio@unipacifico.edu.co', 'hmorenp@unipacifico.edu.co', 'hbenitez@unipacifico.edu.co', 'hernan hildelberg gomez estupiñan', 'jhon cleyber vivas banguera', 'jjmurilloflorez@unipacifico.edu.co', 'jwcaicedo@unipacifico.edu.co', 'jcmolina@unipacifico.edu.co', 'jmanuelh@unipacifico.edu.co', 'lafigueroa@unipacifico.edu.co', 'pedroangulo@unipacifico.edu.co', 'sandra patricia rivera guzman', 'vhvalencia@unipacifico.edu.co', 'wcastillo@unipacifico.edu.co', 'waquinonezv@unipacifico.edu.co', 'ykcaicedo@unipacifico.edu.co') ON CONFLICT (usuario_id, rol_id) DO NOTHING;

-- Asignaturas
INSERT INTO asignaturas (programa_id, codigo, nombre, creditos, activa) SELECT id, 'IS03', 'Analisis De Sistemas', 3, true FROM programas_academicos WHERE codigo = 'ING-SIS' ON CONFLICT (programa_id, codigo) DO NOTHING;
INSERT INTO asignaturas (programa_id, codigo, nombre, creditos, activa) SELECT id, 'IS02', 'Programacion Orientada A Objetos', 3, true FROM programas_academicos WHERE codigo = 'ING-SIS' ON CONFLICT (programa_id, codigo) DO NOTHING;
INSERT INTO asignaturas (programa_id, codigo, nombre, creditos, activa) SELECT id, 'ISO1', 'Algoritmia', 3, true FROM programas_academicos WHERE codigo = 'ING-SIS' ON CONFLICT (programa_id, codigo) DO NOTHING;
INSERT INTO asignaturas (programa_id, codigo, nombre, creditos, activa) SELECT id, 'IS03', 'Estructuras De Datos', 3, true FROM programas_academicos WHERE codigo = 'ING-SIS' ON CONFLICT (programa_id, codigo) DO NOTHING;
INSERT INTO asignaturas (programa_id, codigo, nombre, creditos, activa) SELECT id, 'FORMULACIONDEPROYECT', 'Formulacion De Proyectos', 3, true FROM programas_academicos WHERE codigo = 'ING-SIS' ON CONFLICT (programa_id, codigo) DO NOTHING;
INSERT INTO asignaturas (programa_id, codigo, nombre, creditos, activa) SELECT id, 'IS03', 'Administracion De Empresas', 3, true FROM programas_academicos WHERE codigo = 'ING-SIS' ON CONFLICT (programa_id, codigo) DO NOTHING;
INSERT INTO asignaturas (programa_id, codigo, nombre, creditos, activa) SELECT id, 'IS05', 'Analisis Financiero', 3, true FROM programas_academicos WHERE codigo = 'ING-SIS' ON CONFLICT (programa_id, codigo) DO NOTHING;
INSERT INTO asignaturas (programa_id, codigo, nombre, creditos, activa) SELECT id, 'IS01', 'Introduccion A La Ingenieria De Sistemas', 3, true FROM programas_academicos WHERE codigo = 'ING-SIS' ON CONFLICT (programa_id, codigo) DO NOTHING;
INSERT INTO asignaturas (programa_id, codigo, nombre, creditos, activa) SELECT id, 'IS05', 'Matematicas Discretas', 3, true FROM programas_academicos WHERE codigo = 'ING-SIS' ON CONFLICT (programa_id, codigo) DO NOTHING;
INSERT INTO asignaturas (programa_id, codigo, nombre, creditos, activa) SELECT id, 'IS05', 'Ingenieria Del Software', 3, true FROM programas_academicos WHERE codigo = 'ING-SIS' ON CONFLICT (programa_id, codigo) DO NOTHING;
INSERT INTO asignaturas (programa_id, codigo, nombre, creditos, activa) SELECT id, 'ISO7', 'Ingenieria Economica', 3, true FROM programas_academicos WHERE codigo = 'ING-SIS' ON CONFLICT (programa_id, codigo) DO NOTHING;
INSERT INTO asignaturas (programa_id, codigo, nombre, creditos, activa) SELECT id, 'IS05', 'Electronica Digital', 3, true FROM programas_academicos WHERE codigo = 'ING-SIS' ON CONFLICT (programa_id, codigo) DO NOTHING;
INSERT INTO asignaturas (programa_id, codigo, nombre, creditos, activa) SELECT id, 'IS06', 'Fundamentos De Redes', 3, true FROM programas_academicos WHERE codigo = 'ING-SIS' ON CONFLICT (programa_id, codigo) DO NOTHING;
INSERT INTO asignaturas (programa_id, codigo, nombre, creditos, activa) SELECT id, 'IS06', 'Ingenieria De Procesos', 3, true FROM programas_academicos WHERE codigo = 'ING-SIS' ON CONFLICT (programa_id, codigo) DO NOTHING;
INSERT INTO asignaturas (programa_id, codigo, nombre, creditos, activa) SELECT id, 'ETICAYCONSTITUCION', 'Etica Y Constitucion', 3, true FROM programas_academicos WHERE codigo = 'ING-SIS' ON CONFLICT (programa_id, codigo) DO NOTHING;
INSERT INTO asignaturas (programa_id, codigo, nombre, creditos, activa) SELECT id, 'IS08', 'Electiva Profesional Ii', 3, true FROM programas_academicos WHERE codigo = 'ING-SIS' ON CONFLICT (programa_id, codigo) DO NOTHING;

-- Docentes
INSERT INTO docentes (usuario_id, codigo_docente, activo) SELECT id, 'alvasquez', true FROM usuarios WHERE email = 'alvasquez@unipacifico.edu.co' ON CONFLICT (usuario_id) DO NOTHING;
INSERT INTO docentes (usuario_id, codigo_docente, activo) SELECT id, 'cariascos', true FROM usuarios WHERE email = 'cariascos@unipacifico.edu.co' ON CONFLICT (usuario_id) DO NOTHING;
INSERT INTO docentes (usuario_id, codigo_docente, activo) SELECT id, 'danielhb', true FROM usuarios WHERE email = 'danielhb@unipacifico.edu.co' ON CONFLICT (usuario_id) DO NOTHING;
INSERT INTO docentes (usuario_id, codigo_docente, activo) SELECT id, 'eandrade', true FROM usuarios WHERE email = 'eandrade@unipacifico.edu.co' ON CONFLICT (usuario_id) DO NOTHING;
INSERT INTO docentes (usuario_id, codigo_docente, activo) SELECT id, 'esolisc', true FROM usuarios WHERE email = 'esolisc@unipacifico.edu.co' ON CONFLICT (usuario_id) DO NOTHING;
INSERT INTO docentes (usuario_id, codigo_docente, activo) SELECT id, 'evalois', true FROM usuarios WHERE email = 'evalois@unipacifico.edu.co' ON CONFLICT (usuario_id) DO NOTHING;
INSERT INTO docentes (usuario_id, codigo_docente, activo) SELECT id, 'glucio', true FROM usuarios WHERE email = 'glucio@unipacifico.edu.co' ON CONFLICT (usuario_id) DO NOTHING;
INSERT INTO docentes (usuario_id, codigo_docente, activo) SELECT id, 'hmorenp', true FROM usuarios WHERE email = 'hmorenp@unipacifico.edu.co' ON CONFLICT (usuario_id) DO NOTHING;
INSERT INTO docentes (usuario_id, codigo_docente, activo) SELECT id, 'hbenitez', true FROM usuarios WHERE email = 'hbenitez@unipacifico.edu.co' ON CONFLICT (usuario_id) DO NOTHING;
INSERT INTO docentes (usuario_id, codigo_docente, activo) SELECT id, 'hernanhildelberggomezestupian', true FROM usuarios WHERE email = 'hernan hildelberg gomez estupiñan' ON CONFLICT (usuario_id) DO NOTHING;
INSERT INTO docentes (usuario_id, codigo_docente, activo) SELECT id, 'jhoncleybervivasbanguera', true FROM usuarios WHERE email = 'jhon cleyber vivas banguera' ON CONFLICT (usuario_id) DO NOTHING;
INSERT INTO docentes (usuario_id, codigo_docente, activo) SELECT id, 'jjmurilloflorez', true FROM usuarios WHERE email = 'jjmurilloflorez@unipacifico.edu.co' ON CONFLICT (usuario_id) DO NOTHING;
INSERT INTO docentes (usuario_id, codigo_docente, activo) SELECT id, 'jwcaicedo', true FROM usuarios WHERE email = 'jwcaicedo@unipacifico.edu.co' ON CONFLICT (usuario_id) DO NOTHING;
INSERT INTO docentes (usuario_id, codigo_docente, activo) SELECT id, 'jcmolina', true FROM usuarios WHERE email = 'jcmolina@unipacifico.edu.co' ON CONFLICT (usuario_id) DO NOTHING;
INSERT INTO docentes (usuario_id, codigo_docente, activo) SELECT id, 'jmanuelh', true FROM usuarios WHERE email = 'jmanuelh@unipacifico.edu.co' ON CONFLICT (usuario_id) DO NOTHING;
INSERT INTO docentes (usuario_id, codigo_docente, activo) SELECT id, 'lafigueroa', true FROM usuarios WHERE email = 'lafigueroa@unipacifico.edu.co' ON CONFLICT (usuario_id) DO NOTHING;
INSERT INTO docentes (usuario_id, codigo_docente, activo) SELECT id, 'pedroangulo', true FROM usuarios WHERE email = 'pedroangulo@unipacifico.edu.co' ON CONFLICT (usuario_id) DO NOTHING;
INSERT INTO docentes (usuario_id, codigo_docente, activo) SELECT id, 'sandrapatriciariveraguzman', true FROM usuarios WHERE email = 'sandra patricia rivera guzman' ON CONFLICT (usuario_id) DO NOTHING;
INSERT INTO docentes (usuario_id, codigo_docente, activo) SELECT id, 'vhvalencia', true FROM usuarios WHERE email = 'vhvalencia@unipacifico.edu.co' ON CONFLICT (usuario_id) DO NOTHING;
INSERT INTO docentes (usuario_id, codigo_docente, activo) SELECT id, 'wcastillo', true FROM usuarios WHERE email = 'wcastillo@unipacifico.edu.co' ON CONFLICT (usuario_id) DO NOTHING;
INSERT INTO docentes (usuario_id, codigo_docente, activo) SELECT id, 'waquinonezv', true FROM usuarios WHERE email = 'waquinonezv@unipacifico.edu.co' ON CONFLICT (usuario_id) DO NOTHING;
INSERT INTO docentes (usuario_id, codigo_docente, activo) SELECT id, 'ykcaicedo', true FROM usuarios WHERE email = 'ykcaicedo@unipacifico.edu.co' ON CONFLICT (usuario_id) DO NOTHING;

-- Grupos de asignatura
INSERT INTO grupos_asignatura (asignatura_id, docente_id, codigo_grupo, jornada, activo) SELECT a.id, d.id, 'IS03D1', 'diurna', true FROM asignaturas a JOIN programas_academicos p ON p.id = a.programa_id JOIN docentes d ON d.usuario_id = (SELECT u.id FROM usuarios u WHERE u.email = 'alvasquez@unipacifico.edu.co') WHERE p.codigo = 'ING-SIS' AND a.codigo = 'IS03' ON CONFLICT (asignatura_id, codigo_grupo) DO NOTHING;
INSERT INTO grupos_asignatura (asignatura_id, docente_id, codigo_grupo, jornada, activo) SELECT a.id, d.id, 'IS02D4', 'diurna', true FROM asignaturas a JOIN programas_academicos p ON p.id = a.programa_id JOIN docentes d ON d.usuario_id = (SELECT u.id FROM usuarios u WHERE u.email = 'cariascos@unipacifico.edu.co') WHERE p.codigo = 'ING-SIS' AND a.codigo = 'IS02' ON CONFLICT (asignatura_id, codigo_grupo) DO NOTHING;
INSERT INTO grupos_asignatura (asignatura_id, docente_id, codigo_grupo, jornada, activo) SELECT a.id, d.id, 'ISO1D4', 'diurna', true FROM asignaturas a JOIN programas_academicos p ON p.id = a.programa_id JOIN docentes d ON d.usuario_id = (SELECT u.id FROM usuarios u WHERE u.email = 'danielhb@unipacifico.edu.co') WHERE p.codigo = 'ING-SIS' AND a.codigo = 'ISO1' ON CONFLICT (asignatura_id, codigo_grupo) DO NOTHING;
INSERT INTO grupos_asignatura (asignatura_id, docente_id, codigo_grupo, jornada, activo) SELECT a.id, d.id, 'IS03D3', 'diurna', true FROM asignaturas a JOIN programas_academicos p ON p.id = a.programa_id JOIN docentes d ON d.usuario_id = (SELECT u.id FROM usuarios u WHERE u.email = 'eandrade@unipacifico.edu.co') WHERE p.codigo = 'ING-SIS' AND a.codigo = 'IS03' ON CONFLICT (asignatura_id, codigo_grupo) DO NOTHING;
INSERT INTO grupos_asignatura (asignatura_id, docente_id, codigo_grupo, jornada, activo) SELECT a.id, d.id, '', 'diurna', true FROM asignaturas a JOIN programas_academicos p ON p.id = a.programa_id JOIN docentes d ON d.usuario_id = (SELECT u.id FROM usuarios u WHERE u.email = 'esolisc@unipacifico.edu.co') WHERE p.codigo = 'ING-SIS' AND a.codigo = 'FORMULACIONDEPROYECT' ON CONFLICT (asignatura_id, codigo_grupo) DO NOTHING;
INSERT INTO grupos_asignatura (asignatura_id, docente_id, codigo_grupo, jornada, activo) SELECT a.id, d.id, 'IS03D1', 'diurna', true FROM asignaturas a JOIN programas_academicos p ON p.id = a.programa_id JOIN docentes d ON d.usuario_id = (SELECT u.id FROM usuarios u WHERE u.email = 'evalois@unipacifico.edu.co') WHERE p.codigo = 'ING-SIS' AND a.codigo = 'IS03' ON CONFLICT (asignatura_id, codigo_grupo) DO NOTHING;
INSERT INTO grupos_asignatura (asignatura_id, docente_id, codigo_grupo, jornada, activo) SELECT a.id, d.id, 'IS03D2', 'diurna', true FROM asignaturas a JOIN programas_academicos p ON p.id = a.programa_id JOIN docentes d ON d.usuario_id = (SELECT u.id FROM usuarios u WHERE u.email = 'glucio@unipacifico.edu.co') WHERE p.codigo = 'ING-SIS' AND a.codigo = 'IS03' ON CONFLICT (asignatura_id, codigo_grupo) DO NOTHING;
INSERT INTO grupos_asignatura (asignatura_id, docente_id, codigo_grupo, jornada, activo) SELECT a.id, d.id, 'IS05N1', 'nocturna', true FROM asignaturas a JOIN programas_academicos p ON p.id = a.programa_id JOIN docentes d ON d.usuario_id = (SELECT u.id FROM usuarios u WHERE u.email = 'hmorenp@unipacifico.edu.co') WHERE p.codigo = 'ING-SIS' AND a.codigo = 'IS05' ON CONFLICT (asignatura_id, codigo_grupo) DO NOTHING;
INSERT INTO grupos_asignatura (asignatura_id, docente_id, codigo_grupo, jornada, activo) SELECT a.id, d.id, 'IS01D1', 'diurna', true FROM asignaturas a JOIN programas_academicos p ON p.id = a.programa_id JOIN docentes d ON d.usuario_id = (SELECT u.id FROM usuarios u WHERE u.email = 'hbenitez@unipacifico.edu.co') WHERE p.codigo = 'ING-SIS' AND a.codigo = 'IS01' ON CONFLICT (asignatura_id, codigo_grupo) DO NOTHING;
INSERT INTO grupos_asignatura (asignatura_id, docente_id, codigo_grupo, jornada, activo) SELECT a.id, d.id, 'IS05D1', 'diurna', true FROM asignaturas a JOIN programas_academicos p ON p.id = a.programa_id JOIN docentes d ON d.usuario_id = (SELECT u.id FROM usuarios u WHERE u.email = 'hernan hildelberg gomez estupiñan') WHERE p.codigo = 'ING-SIS' AND a.codigo = 'IS05' ON CONFLICT (asignatura_id, codigo_grupo) DO NOTHING;
INSERT INTO grupos_asignatura (asignatura_id, docente_id, codigo_grupo, jornada, activo) SELECT a.id, d.id, 'IS0207', 'diurna', true FROM asignaturas a JOIN programas_academicos p ON p.id = a.programa_id JOIN docentes d ON d.usuario_id = (SELECT u.id FROM usuarios u WHERE u.email = 'jhon cleyber vivas banguera') WHERE p.codigo = 'ING-SIS' AND a.codigo = 'IS02' ON CONFLICT (asignatura_id, codigo_grupo) DO NOTHING;
INSERT INTO grupos_asignatura (asignatura_id, docente_id, codigo_grupo, jornada, activo) SELECT a.id, d.id, 'IS05D2', 'diurna', true FROM asignaturas a JOIN programas_academicos p ON p.id = a.programa_id JOIN docentes d ON d.usuario_id = (SELECT u.id FROM usuarios u WHERE u.email = 'jjmurilloflorez@unipacifico.edu.co') WHERE p.codigo = 'ING-SIS' AND a.codigo = 'IS05' ON CONFLICT (asignatura_id, codigo_grupo) DO NOTHING;
INSERT INTO grupos_asignatura (asignatura_id, docente_id, codigo_grupo, jornada, activo) SELECT a.id, d.id, 'ISO7N1', 'nocturna', true FROM asignaturas a JOIN programas_academicos p ON p.id = a.programa_id JOIN docentes d ON d.usuario_id = (SELECT u.id FROM usuarios u WHERE u.email = 'jwcaicedo@unipacifico.edu.co') WHERE p.codigo = 'ING-SIS' AND a.codigo = 'ISO7' ON CONFLICT (asignatura_id, codigo_grupo) DO NOTHING;
INSERT INTO grupos_asignatura (asignatura_id, docente_id, codigo_grupo, jornada, activo) SELECT a.id, d.id, 'IS01D3', 'diurna', true FROM asignaturas a JOIN programas_academicos p ON p.id = a.programa_id JOIN docentes d ON d.usuario_id = (SELECT u.id FROM usuarios u WHERE u.email = 'jcmolina@unipacifico.edu.co') WHERE p.codigo = 'ING-SIS' AND a.codigo = 'ISO1' ON CONFLICT (asignatura_id, codigo_grupo) DO NOTHING;
INSERT INTO grupos_asignatura (asignatura_id, docente_id, codigo_grupo, jornada, activo) SELECT a.id, d.id, 'IS05D1', 'diurna', true FROM asignaturas a JOIN programas_academicos p ON p.id = a.programa_id JOIN docentes d ON d.usuario_id = (SELECT u.id FROM usuarios u WHERE u.email = 'jmanuelh@unipacifico.edu.co') WHERE p.codigo = 'ING-SIS' AND a.codigo = 'IS05' ON CONFLICT (asignatura_id, codigo_grupo) DO NOTHING;
INSERT INTO grupos_asignatura (asignatura_id, docente_id, codigo_grupo, jornada, activo) SELECT a.id, d.id, 'IS06D1', 'diurna', true FROM asignaturas a JOIN programas_academicos p ON p.id = a.programa_id JOIN docentes d ON d.usuario_id = (SELECT u.id FROM usuarios u WHERE u.email = 'lafigueroa@unipacifico.edu.co') WHERE p.codigo = 'ING-SIS' AND a.codigo = 'IS06' ON CONFLICT (asignatura_id, codigo_grupo) DO NOTHING;
INSERT INTO grupos_asignatura (asignatura_id, docente_id, codigo_grupo, jornada, activo) SELECT a.id, d.id, 'IS01D1', 'diurna', true FROM asignaturas a JOIN programas_academicos p ON p.id = a.programa_id JOIN docentes d ON d.usuario_id = (SELECT u.id FROM usuarios u WHERE u.email = 'pedroangulo@unipacifico.edu.co') WHERE p.codigo = 'ING-SIS' AND a.codigo = 'ISO1' ON CONFLICT (asignatura_id, codigo_grupo) DO NOTHING;
INSERT INTO grupos_asignatura (asignatura_id, docente_id, codigo_grupo, jornada, activo) SELECT a.id, d.id, 'IS03N1', 'nocturna', true FROM asignaturas a JOIN programas_academicos p ON p.id = a.programa_id JOIN docentes d ON d.usuario_id = (SELECT u.id FROM usuarios u WHERE u.email = 'sandra patricia rivera guzman') WHERE p.codigo = 'ING-SIS' AND a.codigo = 'IS03' ON CONFLICT (asignatura_id, codigo_grupo) DO NOTHING;
INSERT INTO grupos_asignatura (asignatura_id, docente_id, codigo_grupo, jornada, activo) SELECT a.id, d.id, 'IS06N1', 'nocturna', true FROM asignaturas a JOIN programas_academicos p ON p.id = a.programa_id JOIN docentes d ON d.usuario_id = (SELECT u.id FROM usuarios u WHERE u.email = 'vhvalencia@unipacifico.edu.co') WHERE p.codigo = 'ING-SIS' AND a.codigo = 'IS06' ON CONFLICT (asignatura_id, codigo_grupo) DO NOTHING;
INSERT INTO grupos_asignatura (asignatura_id, docente_id, codigo_grupo, jornada, activo) SELECT a.id, d.id, '', 'diurna', true FROM asignaturas a JOIN programas_academicos p ON p.id = a.programa_id JOIN docentes d ON d.usuario_id = (SELECT u.id FROM usuarios u WHERE u.email = 'wcastillo@unipacifico.edu.co') WHERE p.codigo = 'ING-SIS' AND a.codigo = 'ETICAYCONSTITUCION' ON CONFLICT (asignatura_id, codigo_grupo) DO NOTHING;
INSERT INTO grupos_asignatura (asignatura_id, docente_id, codigo_grupo, jornada, activo) SELECT a.id, d.id, 'IS08N1', 'nocturna', true FROM asignaturas a JOIN programas_academicos p ON p.id = a.programa_id JOIN docentes d ON d.usuario_id = (SELECT u.id FROM usuarios u WHERE u.email = 'waquinonezv@unipacifico.edu.co') WHERE p.codigo = 'ING-SIS' AND a.codigo = 'IS08' ON CONFLICT (asignatura_id, codigo_grupo) DO NOTHING;
INSERT INTO grupos_asignatura (asignatura_id, docente_id, codigo_grupo, jornada, activo) SELECT a.id, d.id, 'IS05D1', 'diurna', true FROM asignaturas a JOIN programas_academicos p ON p.id = a.programa_id JOIN docentes d ON d.usuario_id = (SELECT u.id FROM usuarios u WHERE u.email = 'ykcaicedo@unipacifico.edu.co') WHERE p.codigo = 'ING-SIS' AND a.codigo = 'IS05' ON CONFLICT (asignatura_id, codigo_grupo) DO NOTHING;

COMMIT;