# Generated by Django 5.0.14 on 2026-07-21 16:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudades', to='egresados.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilEgresado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PAS', 'Pasaporte')], default='CC', max_length=5)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono_celular', models.CharField(blank=True, max_length=20)),
                ('direccion_residencia', models.CharField(blank=True, max_length=255)),
                ('biografia', models.TextField(blank=True)),
                ('trabaja_actualmente', models.BooleanField(default=False)),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=150)),
                ('contacto_emergencia_parentesco', models.CharField(blank=True, max_length=100)),
                ('contacto_emergencia_telefono', models.CharField(blank=True, max_length=20)),
                ('contacto_emergencia_email', models.EmailField(blank=True, max_length=254)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='egresados.ciudad')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='egresados.departamento')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_egresado', to=settings.AUTH_USER_MODEL)),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='egresados.programa')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=150)),
                ('nit', models.CharField(blank=True, max_length=20)),
                ('sector_economico', models.CharField(blank=True, max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('cargo_actual', models.BooleanField(default=False)),
                ('modalidad', models.CharField(choices=[('Presencial', 'Presencial'), ('Remoto', 'Remoto'), ('Híbrido', 'Híbrido'), ('Freelance', 'Freelance')], max_length=20)),
                ('tipo_contrato', models.CharField(choices=[('Término indefinido', 'Término indefinido'), ('Término fijo', 'Término fijo'), ('Prestación de servicios', 'Prestación de servicios'), ('Obra o labor', 'Obra o labor'), ('Independiente', 'Independiente')], max_length=30)),
                ('rango_salarial', models.CharField(choices=[('Menos de 2 SMMLV', 'Menos de 2 SMMLV'), ('Entre 2 y 4 SMMLV', 'Entre 2 y 4 SMMLV'), ('Entre 4 y 6 SMMLV', 'Entre 4 y 6 SMMLV'), ('Entre 6 y 8 SMMLV', 'Entre 6 y 8 SMMLV'), ('Entre 8 y 10 SMMLV', 'Entre 8 y 10 SMMLV'), ('Más de 10 SMMLV', 'Más de 10 SMMLV')], max_length=30)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='egresados.perfilegresado')),
            ],
        ),
        migrations.CreateModel(
            name='EstudioPosterior',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nivel_estudio', models.CharField(choices=[('Especialización', 'Especialización'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado'), ('Certificación', 'Certificación')], max_length=30)),
                ('institucion', models.CharField(max_length=150)),
                ('titulo', models.CharField(max_length=150)),
                ('pais', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('En curso', 'En curso'), ('Finalizado', 'Finalizado')], default='Finalizado', max_length=20)),
                ('fecha_graduacion', models.DateField(blank=True, null=True)),
                ('anio_finalizacion', models.IntegerField(blank=True, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='egresados.perfilegresado')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoAdjunto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='egresados/documentos/')),
                ('tipo_documento', models.CharField(max_length=100)),
                ('tamano', models.CharField(blank=True, max_length=20)),
                ('fecha_carga', models.DateField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='egresados.perfilegresado')),
            ],
        ),
        migrations.CreateModel(
            name='RedProfesional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plataforma', models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('gitlab', 'GitLab'), ('portafolio', 'Portafolio Personal')], max_length=20)),
                ('url', models.URLField()),
                ('visibilidad', models.CharField(default='publico', max_length=15)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes', to='egresados.perfilegresado')),
            ],
        ),
    ]
