# Generated by Django 5.0.14 on 2026-07-29 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('egresados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilegresado',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_egresado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='egresados.perfilegresado'),
        ),
        migrations.AddField(
            model_name='estudioposterior',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='egresados.perfilegresado'),
        ),
        migrations.AddField(
            model_name='documentoadjunto',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='egresados.perfilegresado'),
        ),
        migrations.AddField(
            model_name='profesorasignatura',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesores_asignados', to='egresados.asignatura'),
        ),
        migrations.AddField(
            model_name='profesorasignatura',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_asignatura', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfilegresado',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='egresados.programa'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='egresados.programa'),
        ),
        migrations.AddField(
            model_name='redprofesional',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes', to='egresados.perfilegresado'),
        ),
        migrations.AlterUniqueTogether(
            name='profesorasignatura',
            unique_together={('profesor', 'asignatura')},
        ),
    ]
