# Generated by Django 5.0.14 on 2026-07-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresados', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilegresado',
            name='validado',
            field=models.BooleanField(default=False),
        ),
    ]
