# Generated by Django 5.0.14 on 2026-08-02 22:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresados', '0004_evento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionEvento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_egresado', models.CharField(max_length=150)),
                ('documento_egresado', models.CharField(max_length=20)),
                ('programa_egresado', models.CharField(blank=True, max_length=150)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('cancelada', models.BooleanField(default=False)),
                ('egresado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_evento', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='egresados.evento')),
            ],
            options={
                'unique_together': {('evento', 'egresado')},
            },
        ),
    ]
