# Generated by Django 5.0.14 on 2026-08-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresados', '0005_inscripcionevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/'),
        ),
    ]
